# Generated by Django 2.2.2 on 2019-06-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Stock',
        ),
    ]
