# Generated by Django 2.2.2 on 2019-06-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_auto_20190627_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='email',
        ),
    ]
