export const FETCH_STOCK = 'FETCH_STOCK';
export const FETCH_STOCKLIST = 'FETCH_STOCKLIST';
export const FETCH_ERROR = 'FETCH_ERROR';
export const PURCHASE_SUCCESSFUL = 'PURCHASE_SUCCESSFUL';
export const SELL_SUCCESSFUL = 'SELL_SUCCESSFUL';
export const SELL_ERROR = 'SELL_ERROR';
<<<<<<< HEAD
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
=======
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const PURCHASE_EXISTING_SUCCESSFUL = 'PURCHASE_EXISTING_SUCCESSFUL';
export const CLEAR_STOCK = 'CLEAR_STOCK';
>>>>>>> staging
