export const FETCH_STOCK = 'FETCH_STOCK';
export const FETCH_STOCKLIST = 'FETCH_STOCKLIST';
export const FETCH_ERROR = 'FETCH_ERROR';
export const PURCHASE_SUCCESSFUL = 'PURCHASE_SUCCESSFUL';
export const SELL_SUCCESSFUL = 'SELL_SUCCESSFUL';
export const SELL_ERROR = 'SELL_ERROR';
export const UPDATE_PRICE = 'UPDATE_PRICE';